export const searchApiActionType = {
    GET_SEARCHAPI_E1_SUCCESS: "[WA] GET_SEARCHAPI_E1_SUCCESS",
    GET_SEARCHAPI_E1_FAIL: "[WA] GET_SEARCHAPI_E1_FAIL",

    GET_SEARCHAPI_E2_SUCCESS: "[WA] GET_SEARCHAPI_E2_SUCCESS",
    GET_SEARCHAPI_E2_FAIL: "[WA] GET_SEARCHAPI_E2_FAIL",

    GET_SEARCHAPI_E3_SUCCESS: "[WA] GET_SEARCHAPI_E3_SUCCESS",
    GET_SEARCHAPI_E3_FAIL: "[WA] GET_SEARCHAPI_E3_FAIL",
}